cuda: True
FeedforwardNeuralNetModel(
  (fc1): Linear(in_features=784, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=32, bias=True)
  (relu): ReLU()
  (fc3): Linear(in_features=32, out_features=10, bias=True)
  (log_relu): ReLU()
  (logger1): LoggerLayer(
    (layer): ReLU()
  )
  (logger2): LoggerLayer(
    (layer): ReLU()
  )
  (logger3): LoggerLayer(
    (layer): Linear(in_features=32, out_features=10, bias=True)
  )
  (d1): Dropout(p=0.25, inplace=False)
  (d2): Dropout(p=0.25, inplace=False)
)
torch.Size([256, 784])
batch_size: 100, lr: 0.1, path lambda: 0.01, p: 2.0, l1: 0.0, optimizer: Adadelta (
Parameter Group 0
    eps: 1e-06
    initial_lr: 0.1
    lr: 0.1
    rho: 0.9
    weight_decay: 0
)
epochs are 5
  0%|          | 0/5 [00:00<?, ?it/s]
0it [00:00, ?it/s][Aterminate called after throwing an instance of 'c10::Error'
  what():  output with shape [] doesn't match the broadcast shape [1, 1]
Exception raised from mark_resize_outputs at /tmp/coulombc/pytorch_build_2021-11-10_08-09-16/avx2/python3.9/pytorch/aten/src/ATen/TensorIterator.cpp:1044 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b1d08f21905 in /home/aweiss13/ENVS/pytorch/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xdb (0x2b1d08f03185 in /home/aweiss13/ENVS/pytorch/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: at::TensorIteratorBase::mark_resize_outputs(at::TensorIteratorConfig const&) + 0x281 (0x2b1ce391bb21 in /home/aweiss13/ENVS/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job56866242/slurm_script: line 10: 30269 Aborted                 (core dumped) python ./main.py --lr=0.1 --batch-size=100 --epochs=5 --p=2 --lambda-pr=.01
